# Generated by Django 3.2.12 on 2022-03-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contect',
        ),
    ]
