# Generated by Django 3.2.12 on 2022-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_contect'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contect',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
    ]
